### ISSUE TITLE
박창수 학생에게

### ISSUE THREAD

**Issue by laftworld** [chsupark/dotfiles#1]
창수학생은 대만으로 떠났다고 하더군요:)  
조심히 잘 다녀오기 바랍니다. 

연락처가 없어 Github issue로 글을 남깁니다.
아래 링크를 클릭하시면 마지막 안내글을 보실 수 있습니다.
[마지막 안내글](https://docs.google.com/document/d/1gUlmj-GbiC44srczMRQ-dVSvnPtTukUmGcXr4Xut4bA/edit?usp=sharing)

홍원의 드림

**Comment by chsupark** [comment]
감사합니다 선생님 :)
2일동안 재미있는 강의 들을 수 있어 좋았습니다.
